class OFFSET_REGIONS_SIZE:
    DIALOG_WIDTH: int = 880
    DIALOG_HEIGHT: int = 720
    FIELD_WIDTH: int = 240
    DETAILS_DIALOG_WIDTH: int = 540
    DETAILS_DIALOG_HEIGHT: int = 360


class OFFSET_REGIONS_SPACING:
    ROOT: int = 15
    DETAILS_DIALOG: int = 16
