class OFFSET_REGIONS_SIZE:
    DIALOG_WIDTH: int = 780
    DIALOG_HEIGHT: int = 720
    DETAILS_DIALOG_WIDTH: int = 540
    DETAILS_DIALOG_HEIGHT: int = 360


class OFFSET_REGIONS_SPACING:
    ROOT: int = 15
    DETAILS_DIALOG: int = 16
