class OFFSET_REGIONS_SIZE:
    DIALOG_MIN_WIDTH: int = 1000
    DIALOG_MIN_HEIGHT: int = 600
    DIALOG_WIDTH: int = 1100
    DIALOG_HEIGHT: int = 720
    DIALOG_MAX_WIDTH: int = 1380
    DIALOG_MAX_HEIGHT: int = 1280
    FIELD_WIDTH: int = 240
    DETAILS_DIALOG_WIDTH: int = 540
    DETAILS_DIALOG_HEIGHT: int = 360


class OFFSET_REGIONS_SPACING:
    ROOT: int = 15
    DETAILS_DIALOG: int = 16
