ANSI_WINDOWS_ENCODING = "cp1252"
BINARY_WORKBENCH_ANSI_TABLE_NAME = "ASCII (ANSI windows)"

BINARY_WORKBENCH_ROW_BYTES = 4
BINARY_WORKBENCH_FILE_OFFSET_COLUMN = "File"
BINARY_WORKBENCH_DEFAULT_FILE_OFFSET = "0x00000000"
BINARY_WORKBENCH_EMPTY_OFFSET = "-"
ASSEMBLY_LABEL_SEPARATOR = ":"

BINARY_WORKBENCH_DEFAULT_BLOCK_SIZE: int = 2048
BINARY_WORKBENCH_DEFAULT_CACHE_MAX_BLOCKS: int = 8000
BINARY_WORKBENCH_DEFAULT_SEARCH_RESULT_LIMIT: int = 200
BINARY_WORKBENCH_FIND_DEFAULT_LENGTH_KB: int = 2 * 1024
BINARY_WORKBENCH_FIND_MAX_LENGTH_KB: int = 50 * 1024
BINARY_WORKBENCH_FIND_MAX_LENGTH_BYTES: int = BINARY_WORKBENCH_FIND_MAX_LENGTH_KB * 1024
BINARY_WORKBENCH_SEARCH_CHUNK_SIZE: int = 2 * 1024 * 1024
BINARY_WORKBENCH_SEARCH_EVENT_CHUNKS: int = 4
BINARY_WORKBENCH_DEFAULT_LBA_SECTOR_SIZE: int = 2352
BINARY_WORKBENCH_DEFAULT_VERSION_NAME: str = "default"
BINARY_WORKBENCH_PSX_MIPS_R3000A_DISPLAY_NAME: str = "PSX - Mips R3000A"

BINARY_WORKBENCH_BLOCK_SIZE_OPTIONS: tuple[int, ...] = (
    256,
    512,
    1024,
    2048,
    4096,
)
BINARY_WORKBENCH_CACHE_MAX_BLOCKS_OPTIONS: tuple[int, ...] = (
    1000,
    2000,
    4000,
    8000,
    16000,
)
BINARY_WORKBENCH_BYTE_GROUP_OPTIONS: tuple[int, ...] = (1, 2, 4)
BINARY_WORKBENCH_LBA_SECTOR_SIZE_OPTIONS: tuple[int, ...] = (2048, 2334, 2352)


class BINARY_WORKBENCH_STATE:
    OPEN_FILE_DIRECTORY: str = "open_file"
    OPEN_BINARY_DIRECTORY: str = "open_file"
    OPEN_ASSEMBLY_DIRECTORY: str = "open_assembly"
    SAVE_FILE_DIRECTORY: str = "save_file"
    SAVE_ASSEMBLY_DIRECTORY: str = "save_assembly"
    LBA_FILESYSTEM_DIRECTORY: str = "lba_filesystem"
    SYMBOLS_DIRECTORY: str = "symbols"
    VERSIONS_DIRECTORY: str = "versions"
    ENCODING_TABLES_DIRECTORY: str = "encoding_tables"
    OFFSET_REGIONS_DIRECTORY: str = "offset_regions"
    COMMANDS_DIRECTORY: str = "commands"


class BINARY_WORKBENCH_TAB_KIND:
    BINARY: str = "binary"
    ASSEMBLY: str = "assembly"
    SCRATCH: str = "scratch"
    INTERNAL: str = "internal"
