ANSI_WINDOWS_ENCODING = "cp1252"
BINARY_WORKBENCH_ANSI_TABLE_NAME = "ASCII (ANSI windows)"

BINARY_WORKBENCH_ROW_BYTES = 4
BINARY_WORKBENCH_FILE_OFFSET_COLUMN = "File"
BINARY_WORKBENCH_DEFAULT_FILE_OFFSET = "0x00000000"
BINARY_WORKBENCH_EMPTY_OFFSET = "-"
ASSEMBLY_LABEL_SEPARATOR = ":"
