DECIMAL_DIGITS = "0123456789"
BINARY_DIGITS = "01"
HEX_DIGITS_LOWER = f"{DECIMAL_DIGITS}abcdef"
HEX_DIGITS_UPPER = f"{DECIMAL_DIGITS}ABCDEF"
HEX_DIGITS = f"{HEX_DIGITS_LOWER}ABCDEF"
HEX_KEYS: tuple[str, ...] = tuple(HEX_DIGITS_UPPER)

DECIMAL_INPUT_PATTERN = rf"[{DECIMAL_DIGITS}]*"
HEX_INPUT_PATTERN = rf"[{HEX_DIGITS}]*"
HEX_LOWER_INPUT_PATTERN = rf"[{HEX_DIGITS_LOWER}]*"
HEX_DIGIT_PATTERN = rf"[{HEX_DIGITS}]"
HEX_UPPER_DIGIT_PATTERN = rf"[{HEX_DIGITS_UPPER}]"
