"""Performance budgets for Symbol-derived work."""

ORDINARY_SLICE_BUDGET_MS = 80
EXTRAORDINARY_SLICE_TARGET_MS = 80
EXTRAORDINARY_SLICE_LIMIT_MS = 200
MASS_OPERATION_LIMIT_MS = 2000
TARGET_BATCH_DURATION_MS = 65
MAX_SYMBOL_BATCH_SIZE = 256
MIN_SYMBOL_BATCH_SIZE = 16
SCHEDULER_AGING_MS = 280
SCROLL_FRAME_MS = 16
PREFETCH_DELAY_MS = 50
PREFETCH_FORWARD_LINES = 64
PREFETCH_BACKWARD_LINES = 32
