class BINARY_WORKBENCH_TIMING:
    STATUS_MESSAGE_VISIBLE_MS: int = 3000
    EDITOR_COMPLETION_NAVIGATION_DEBOUNCE_MS: int = 1500
    INCREMENTAL_PROPAGATION_MS: int = 80
    CONSISTENCY_VISUAL_DEBOUNCE_MS: int = 80
    CONSISTENCY_VISUAL_MAX_LATENCY_MS: int = 280
    CONSISTENCY_SEMANTIC_DEBOUNCE_MS: int = 1000
