class BINARY_WORKBENCH_VIEW_LAYOUT:
    DIALOG_WIDTH: int = 300
    MARGIN: int = 20
    LAYOUT_SPACING: int = 0
    BUTTON_WIDTH: int = 252
    IDENTICAL_ITEM_SPACING: int = 15
    CONFIRM_TOP_SPACING: int = 30
