"""Tunable non-visual limits for editor consistency processing."""

CONTRIBUTION_CHUNK_SIZE = 256
OFFSET_BATCH_SIZE = 128
VIEWPORT_MARGIN_LINES = 64
BACKGROUND_CPU_DUTY_FRACTION = 0.25
BACKGROUND_THROTTLE_MAX_SLEEP_SECONDS = 0.05
