class ENCODING_TABLES_SIZE:
    DIALOG_WIDTH: int = 280
    DIALOG_HEIGHT: int = 440


class ENCODING_TABLES_SPACING:
    CONTROL: int = 14


class ENCODING_TABLES_TIMING:
    CONFLICT_MS: int = 3000
