"""Debugger window geometry and panel layout constants."""


class DEBUGGER_LAYOUT:
    """Keep debugger dimensions aligned with the established design system."""

    WINDOW_WIDTH = 1280
    WINDOW_HEIGHT = 820
    MIN_WIDTH = 900
    MIN_HEIGHT = 620
    OUTER_MARGIN = 20
    PANEL_GAP = 30
    TOOLBAR_SPACING = 8
    TOOLBAR_BUTTON_MIN_WIDTH = 92
    TOOLBAR_BUTTON_HEIGHT = 34
    INSTRUCTION_REGISTER_SIZES = (900, 320)
    TOP_BOTTOM_SIZES = (520, 240)
    MEMORY_ROWS = 16
    MEMORY_BYTES_PER_ROW = 16
    STACK_ROWS = 16
    TABLE_ROW_HEIGHT = 26
    REGISTER_ROW_HEIGHT = TABLE_ROW_HEIGHT + 12
    TABLE_CELL_PADDING = 6
    SYNTAX_CELL_LEFT_PADDING = TABLE_CELL_PADDING + 6
    TABLE_SCROLLBAR_GAP = 10
    LOWER_TABLE_ROW_HEIGHT = TABLE_ROW_HEIGHT + 12
    INSTRUCTION_COLUMN_ADJUSTMENTS = (0, 40, 40, 0, 40, 0)
    RAW_INSTRUCTION_COLUMN = 3
    RAW_INSTRUCTION_WIDTH = 210
    INSTRUCTION_STATUS_COLUMN = 5
    INSTRUCTION_STATUS_WIDTH = 120
    REGISTER_PANEL_MAX_WIDTH = 480
    REGISTER_COLUMN_LIMITS = ((30, 70), (140, 180), (100, 160))
    STACK_COLUMN_ADJUSTMENTS = (0, 40, 40)
    MEMORY_BYTE_COLUMNS = 4
    MEMORY_BYTES_PER_CELL = 4
    BREAKPOINT_COLUMN_ADJUSTMENTS = (40, -100, 40)
    BREAKPOINT_ENTRY_HEIGHT = 42
    FILTER_DEBOUNCE_MS = 2000
    FILTER_WIDTH = 180
    CONFIG_DIALOG_WIDTH = 320
    CONFIG_DIALOG_HEIGHT = 130
    CONFIG_FIELD_WIDTH = 260


DEBUGGER_STATE_FILENAME = "debugger_windows.json"
