"""Debugger window geometry and panel layout constants."""


class DEBUGGER_LAYOUT:
    """Keep debugger dimensions aligned with the established design system."""

    WINDOW_WIDTH = 1280
    WINDOW_HEIGHT = 820
    MIN_WIDTH = 900
    MIN_HEIGHT = 620
    OUTER_MARGIN = 20
    PANEL_GAP = 30
    TOOLBAR_SPACING = 8
    TOOLBAR_BUTTON_MIN_WIDTH = 92
    TOOLBAR_BUTTON_HEIGHT = 34
    INSTRUCTION_REGISTER_SIZES = (900, 320)
    TOP_BOTTOM_SIZES = (520, 240)
    MEMORY_ROWS = 16
    MEMORY_BYTES_PER_ROW = 16
    STACK_ROWS = 16
    TABLE_ROW_HEIGHT = 26
    REGISTER_ROW_HEIGHT = TABLE_ROW_HEIGHT + 12
    TABLE_CELL_PADDING = 6
    PANEL_BORDER_WIDTH = 1
    SYNTAX_CELL_LEFT_PADDING = TABLE_CELL_PADDING + 6
    TABLE_SCROLLBAR_GAP = 10
    LOWER_TABLE_ROW_HEIGHT = TABLE_ROW_HEIGHT + 12
    INSTRUCTION_COLUMN_ADJUSTMENTS = (0, 40, 40, 0, 40, 0)
    INSTRUCTION_NUMBER_COLUMN = 0
    INSTRUCTION_NUMBER_MIN_WIDTH = 60
    INSTRUCTION_ADDRESS_COLUMN = 1
    INSTRUCTION_ADDRESS_MIN_WIDTH = 140
    INSTRUCTION_BYTES_COLUMN = 2
    INSTRUCTION_BYTES_MIN_WIDTH = 140
    RAW_INSTRUCTION_COLUMN = 3
    RAW_INSTRUCTION_WIDTH = 250
    INSTRUCTION_ORIGIN_COLUMN = 4
    INSTRUCTION_ORIGIN_MIN_WIDTH = 230
    INSTRUCTION_STATUS_COLUMN = 5
    INSTRUCTION_STATUS_WIDTH = 160
    INSTRUCTION_COLUMN_MINIMUMS = (
        INSTRUCTION_NUMBER_MIN_WIDTH,
        INSTRUCTION_ADDRESS_MIN_WIDTH,
        INSTRUCTION_BYTES_MIN_WIDTH,
        RAW_INSTRUCTION_WIDTH,
        INSTRUCTION_ORIGIN_MIN_WIDTH,
        INSTRUCTION_STATUS_WIDTH,
    )
    REGISTER_PANEL_MAX_WIDTH = 480
    REGISTER_COLUMN_WIDTHS = (55, 130, 155)
    STACK_COLUMN_MINIMUMS = (80, 160, 160, 200)
    STACK_COLUMN_MAXIMUMS = (240, 480, 1800, 3000)
    STACK_GROWTH_COLUMNS = (2, 3)
    STACK_COMPENSATION_COLUMNS = (3, 2, 1, 0)
    MEMORY_BYTE_COLUMNS = 4
    MEMORY_BYTES_PER_CELL = 4
    MEMORY_ADDRESS_COLUMN_WIDTH = 160
    MEMORY_COLUMN_MINIMUMS = (MEMORY_ADDRESS_COLUMN_WIDTH, 96, 96, 96, 96)
    MEMORY_COLUMN_MAXIMUMS = (360, 1024, 1024, 1024, 1024)
    MEMORY_GROWTH_COLUMNS = (1, 2, 3, 4)
    MEMORY_COMPENSATION_COLUMNS = (4, 3, 2, 1, 0)
    MEMORY_FOOTER_LEFT_MARGIN = 15
    MEMORY_FOLLOW_RIGHT_MARGIN = 20
    MEMORY_FOLLOW_TOP_MARGIN = 0
    MEMORY_FOLLOW_BOTTOM_MARGIN = 8
    MEMORY_SEARCH_MIN_WIDTH = 270
    BREAKPOINT_COLUMN_MINIMUMS = (100, 160, 100, 100, 120)
    BREAKPOINT_COLUMN_MAXIMUMS = (100, 3090, 170, 220, 360)
    BREAKPOINT_GROWTH_COLUMNS = (3, 2, 1)
    BREAKPOINT_COMPENSATION_COLUMNS = (1, 3, 2, 4, 0)
    BREAKPOINT_TYPE_COLUMN = 0
    BREAKPOINT_WHERE_COLUMN = 1
    BREAKPOINT_NAME_COLUMN = 2
    BREAKPOINT_INSTRUCTION_COLUMN = 3
    BREAKPOINT_STATUS_COLUMN = 4
    BREAKPOINT_TYPE_EDITOR_HEIGHT_DELTA = 8
    BREAKPOINT_ENTRY_HEIGHT = 42
    FILTER_DEBOUNCE_MS = 2000
    FILTER_WIDTH = 270
    FILTER_ICON_SIZE = 16
    FILTER_ICON_DEFAULT_MARGIN = 12
    FILTER_ICON_TEXT_GAP = 4
    LOG_FILTER_ICON_MARGIN = 15
    LOG_MAX_LINES = 100_000
    CONFIG_DIALOG_WIDTH = 320
    CONFIG_DIALOG_HEIGHT = 144
    CONFIG_LOG_DIALOG_HEIGHT = 272
    CONFIG_FIELD_WIDTH = 180
    CONFIG_CONFIRM_WIDTH = 160
    CONFIG_VERTICAL_SPACING = 20
    CONFIG_LOG_COLUMNS = 3
    CONFIG_LOG_OPTION_SPACING = 8


DEBUGGER_STATE_FILENAME = "debugger_windows.json"
