class BINARY_WORKBENCH_TEXT:
    TITLE: str = "Binary Workbench"
    STATUS_IDLE: str = "Ready."
    STATUS_PLACEHOLDER_TEMPLATE: str = '"{name}" is not implemented yet.'
    STATUS_OPENED_TEMPLATE: str = 'Opened "{name}".'
    STATUS_CLOSED_TEMPLATE: str = 'Closed "{name}".'
    STATUS_INTERNAL_SOURCE_REQUIRED: str = (
        "Select a file-backed tab before opening an internal file."
    )
    STATUS_INTERNAL_FILES_REQUIRED: str = "Configure the LBA File System before opening an internal file."
    STATUS_BINARY_REQUIRED: str = "Open a binary tab before using this action."
    STATUS_VERSION_REQUIRED: str = "Use or load a version before saving a new binary file."
    STATUS_NO_VERSIONS: str = "Create or load a version before using this action."
    STATUS_VERSION_CREATED_TEMPLATE: str = 'Created version "{name}".'
    STATUS_VERSION_UPDATED_TEMPLATE: str = 'Updated version "{name}".'
    STATUS_VERSION_LOADED_TEMPLATE: str = 'Loaded version "{name}".'
    STATUS_FILE_SAVED_TEMPLATE: str = 'Saved new binary file "{name}".'
    FILE: str = "File"
    ENVIRONMENT: str = "Environment"
    PREFERENCES: str = "Preferences"
    SEARCH: str = "Search"
    HELP: str = "Help"
    OPEN_FILE: str = "Open File"
    OPEN_BINARY: str = "Open File"
    OPEN_ASSEMBLY_CODE: str = "Open Assembly / Code"
    NEW_SCRATCH_CODE: str = "New Scratch Code"
    OPEN_INTERNAL_FILE: str = "Open Internal File"
    CREATE_VERSION: str = "Create a Version"
    ATT_CURRENT_VERSION: str = "Att Version"
    LOAD_VERSION: str = "Load a Version"
    SAVE_BINARY_FILE: str = "Save File"
    SAVE_ASSEMBLY_CODE: str = "Save Assembly / Code"
    SYMBOLS: str = "Symbols"
    REGIONS: str = "Memory Regions"
    LBA_FILESYSTEM: str = "LBA File System"
    LABELS: str = "Labels"
    ENCODING_TABLES: str = "Encoding Tables"
    VARIABLES: str = "Variables"
    EQUATES: str = "Equates"
    VIEW: str = "View"
    ADVANCED_CONFIGURATION: str = "Advanced Configuration"
    BYTES_FORMATTER: str = "Bytes Formatter"
    REFERENCE_OFFSETS: str = "Reference Offsets"
    GO_TO: str = "Go to"
    FIND: str = "Find"
    SELECT_BLOCK: str = "Select Block"
    SELECT_ALL: str = "Select All"
    FILE_OFFSET: str = "File"
    RAM_OFFSET: str = "RAM"
    SLUS_OFFSET: str = "SLUS"
    INSTRUCTION: str = "Instruction"
    BYTES: str = "Bytes"
    AUTO_READ_MODE: str = "Auto"
    BYTES_READ_MODE: str = "Bytes"
    ASSEMBLY_READ_MODE: str = "Assembly Text"
    PAGE_TEMPLATE: str = "Page {current} / {total}"
    PAGE_JUMP_PLACEHOLDER: str = "..."
    SELECTION_EMPTY: str = "Selected: none | Length: 0 bytes"
    FILE_FILTER_BINARY: str = "Binary files (*.*)"
    FILE_FILTER_ASSEMBLY: str = "Assembly / code files (*.asm *.s *.txt *.c *.cpp *.*)"
    FILE_FILTER_ANY: str = "All supported files (*.asm *.s *.*)"
    FILE_FILTER_OUTPUT: str = "Binary files (*.bin);;All files (*.*)"
    SYMBOLS_TITLE: str = "Symbols"
    SYMBOLS_SUBTITLE: str = "Manage Variables, Equates and Labels used by the pre-parser."
    SYMBOL_TYPE: str = "Select"
    SYMBOL_NAME: str = "Name"
    SYMBOL_VALUE: str = "Value"
    SYMBOL_ADD: str = "+ Add"
    REFERENCE_OFFSETS_SUBTITLE: str = "Configure up to three extra offset columns."
    REFERENCE_NAME: str = "Name"
    REFERENCE_BASE: str = "Base at File 0x0"
    REFERENCE_VISIBLE: str = "Visible"
    GO_TO_SUBTITLE: str = "Navigate by offset, LBA or future symbolic targets."
    FIND_SUBTITLE: str = "Search assembly, bytes or future decoded text."
    SELECT_BLOCK_SUBTITLE: str = "Select a block by start/end or start/length."
    TARGET_TYPE: str = "Target Type"
    VALUE: str = "Value"
    START_OFFSET: str = "Start Offset"
    END_OFFSET: str = "End Offset"
    LENGTH_BYTES: str = "Length Bytes"
    FILE_OFFSET_TARGET: str = "File Offset"
    LBA_2048_TARGET: str = "LBA (2048 bytes)"
    LBA_2334_TARGET: str = "LBA (2334 bytes)"
    LBA_2352_TARGET: str = "LBA (2352 bytes)"
    LABEL_TARGET: str = "Label"
    EQUATE_TARGET: str = "Equate"
    VARIABLE_TARGET: str = "Variable"
    INTERNAL_FILE_TARGET: str = "Named File / Internal File"
    FIND_ASSEMBLY: str = "Assembly instruction"
    FIND_HEX_BYTES: str = "Hex bytes"
    FIND_DECODED_TEXT: str = "Decoded Text"
    STATUS_NOT_FOUND: str = "No match found."
    STATUS_TARGET_PENDING: str = "This target type is available but not implemented yet."
    STATUS_MULTIPLE_TARGETS: str = "Select one result to navigate."
    STATUS_NO_FOCUSED_EDITOR: str = "Focus Bytes or Instruction before saving."
    SAVE_BEFORE_CLOSE: str = "Save changes before closing this tab?"


class BINARY_WORKBENCH_TAB_KIND:
    BINARY: str = "binary"
    ASSEMBLY: str = "assembly"
    SCRATCH: str = "scratch"
    INTERNAL: str = "internal"


class BINARY_WORKBENCH_LAYOUT:
    WINDOW_WIDTH: int = 920
    WINDOW_HEIGHT: int = 560
    MIN_WIDTH: int = 720
    MIN_HEIGHT: int = 420
    ROOT_LEFT: int = 0
    ROOT_TOP: int = 0
    ROOT_RIGHT: int = 0
    ROOT_BOTTOM: int = 0
    BODY_LEFT: int = 24
    BODY_TOP: int = 24
    BODY_RIGHT: int = 24
    BODY_BOTTOM: int = 24
    BODY_SPACING: int = 20
    TAB_SPACING: int = 12
    TAB_MIN_WIDTH: int = 150
    TAB_MAX_WIDTH: int = 150
    TAB_MIN_HEIGHT: int = 22
    TAB_HORIZONTAL_PADDING: int = 8
    TAB_VERTICAL_PADDING: int = 3
    TAB_RIGHT_MARGIN: int = 4
    TAB_CLOSE_BUTTON_SIZE: int = 10
    TAB_MAX_CHARACTERS: int = 24
    GRID_BYTES_WIDTH: int = 136
    PAGE_TOP_MARGIN: int = 20
    SUMMARY_TOP_MARGIN: int = 35
    SUMMARY_BOTTOM_MARGIN: int = 20
    STATUS_LEFT_MARGIN: int = 24
    STATUS_BOTTOM_MARGIN: int = 8
    STATUS_TOP_MARGIN: int = 8
    EDITOR_SPACING: int = 20
    PANEL_LABEL_SPACING: int = 8
    EDITOR_OFFSET_WIDTH: int = 132
    EDITOR_BYTES_WIDTH: int = 160
    EDITOR_CANVAS_EXTRA_HEIGHT: int = 40
    EDITOR_PANEL_HEADER_HEIGHT: int = 32
    EDITOR_MIN_HEIGHT: int = 120
    EDITOR_MAX_VISIBLE_ROWS: int = 48
    EDITOR_VISIBLE_ROW_SAFETY: int = 2
    EDITOR_DOCUMENT_MARGIN: int = 10
    LOAD_MORE_SCROLL_THRESHOLD: int = 80
    WHEEL_SCROLL_DIVISOR: int = 8
    DEFAULT_BLOCK_SIZE: int = 2048
    DEFAULT_CACHE_MAX_BLOCKS: int = 8000
    PAGE_ROWS: int = 16
    PAGINATION_ITEM_WIDTH: int = 34
    PAGINATION_ELLIPSIS_WIDTH: int = 48


class BINARY_WORKBENCH_STATE:
    OPEN_FILE_DIRECTORY: str = "open_file"
    OPEN_BINARY_DIRECTORY: str = "open_file"
    OPEN_ASSEMBLY_DIRECTORY: str = "open_assembly"
    SAVE_FILE_DIRECTORY: str = "save_file"
    SAVE_ASSEMBLY_DIRECTORY: str = "save_assembly"
    RECENT_FILES_LIMIT: int = 12
